<input type="text" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
<textarea id="text_editor" style="width:400px; height:200px;"></textarea>

<table id="temp-table" class="fxd_header">
    <thead>
        <tr>
            <th colspan="1">Month</th>
            <th colspan="2">Minimum Temp</th>
            <th colspan="2">Rainfall Days</th>
            <th colspan="2">Rainfall Days</th>
            <th colspan="2">Rainfall Days</th>
            <th colspan="2">Rainfall Days</th>
            <th colspan="2">Rainfall Days</th>
        </tr>
        <tr>
            <th>Month</th>
            <th>Minimum Temp</th>
            <th>Maximum Temp</th>
            <th>Precipitaion (mm)</th>
            <th>Rainfall Days</th>
            <th>Precipitaion (mm)</th>
            <th>Rainfall Days</th>
            <th>Precipitaion (mm)</th>
            <th>Rainfall Days</th>
            <th>Precipitaion (mm)</th>
            <th>Rainfall Days</th>
            <th>Precipitaion (mm)</th>
            <th>Rainfall Days</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Jaunuary</th>
            <td>3</td>
            <td>8</td>
            <td>17.8</td>
            <td>10</td>
            <td>17.8</td>
            <td>10</td>
            <td>17.8</td>
            <td>10</td>
            <td>17.8</td>
            <td>10</td>
            <td>17.8</td>
            <td>10</td>
        </tr>
        <tr>
            <th>February</th>
            <td>2</td>
            <td>9</td>
            <td>21.7</td>
            <td>9</td>
            <td>21.7</td>
            <td>9</td>
            <td>21.7</td>
            <td>9</td>
            <td>21.7</td>
            <td>9</td>
            <td>21.7</td>
            <td>9</td>
        </tr>
        <tr>
            <th>March</th>
            <td>4</td>
            <td>13</td>
            <td>24.2</td>
            <td>10</td>
            <td>24.2</td>
            <td>10</td>
            <td>24.2</td>
            <td>10</td>
            <td>24.2</td>
            <td>10</td>
            <td>24.2</td>
            <td>10</td>
        </tr>
        <tr>
            <th>April</th>
            <td>6</td>
            <td>15</td>
            <td>24.6</td>
            <td>11</td>
            <td>24.6</td>
            <td>11</td>
            <td>24.6</td>
            <td>11</td>
            <td>24.6</td>
            <td>11</td>
            <td>24.6</td>
            <td>11</td>
        </tr>
        <tr>
            <th>May</th>
            <td>10</td>
            <td>20</td>
            <td>26.2</td>
            <td>10</td>
            <td>26.2</td>
            <td>10</td>
            <td>26.2</td>
            <td>10</td>
            <td>26.2</td>
            <td>10</td>
            <td>26.2</td>
            <td>10</td>
        </tr>
        <tr>
            <th>June</th>
            <td>13</td>
            <td>23</td>
            <td>25.1</td>
            <td>9</td>
            <td>25.1</td>
            <td>9</td>
            <td>25.1</td>
            <td>9</td>
            <td>25.1</td>
            <td>9</td>
            <td>25.1</td>
            <td>9</td>
        </tr>
        <tr>
            <th>July</th>
            <td>15</td>
            <td>25</td>
            <td>21.7</td>
            <td>7</td>
            <td>21.7</td>
            <td>7</td>
            <td>21.7</td>
            <td>7</td>
            <td>21.7</td>
            <td>7</td>
            <td>21.7</td>
            <td>7</td>
        </tr>
        <tr>
            <th>August</th>
            <td>15</td>
            <td>25</td>
            <td>21.4</td>
            <td>7</td>
            <td>21.4</td>
            <td>7</td>
            <td>21.4</td>
            <td>7</td>
            <td>21.4</td>
            <td>7</td>
            <td>21.4</td>
            <td>7</td>
        </tr>
        <tr>
            <th>September</th>
            <td>11</td>
            <td>21</td>
            <td>15.6</td>
            <td>8</td>
            <td>15.6</td>
            <td>8</td>
            <td>15.6</td>
            <td>8</td>
            <td>15.6</td>
            <td>8</td>
            <td>15.6</td>
            <td>8</td>
        </tr>
        <tr>
            <th>October</th>
            <td>9</td>
            <td>17</td>
            <td>25.3</td>
            <td>11</td>
            <td>25.3</td>
            <td>11</td>
            <td>25.3</td>
            <td>11</td>
            <td>25.3</td>
            <td>11</td>
            <td>25.3</td>
            <td>11</td>
        </tr>
        <tr>
            <th>November</th>
            <td>5</td>
            <td>11</td>
            <td>22.4</td>
            <td>12</td>
            <td>22.4</td>
            <td>12</td>
            <td>22.4</td>
            <td>12</td>
            <td>22.4</td>
            <td>12</td>
            <td>22.4</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
        <tr>
            <th>December</th>
            <td>3</td>
            <td>8</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
            <td>26.6</td>
            <td>12</td>
        </tr>
    </tbody>
</table>

